### ISSUE TITLE
New feature is you can add

### ISSUE THREAD

**Issue by rajeshdharma81** [dharmrajesh/Messanger#6]
Dear Dharm rajesh,

        Your product is very valuable for current market.  As I am going to suggest new feature kindly review it.  If it is valid you can add with your original code

**Comment by dharmrajesh** [comment]
Dear Rajesh dharma,

           Your code is valid for my project.  Thanks for your contribute.

**Comment by dharmrajesh** [comment]
Dear Rajesh dharma,
    Your code is added with my original code
